#!/bin/sh
#
# Default fetchmail ip-down script (/etc/ppp/ip-down.d/fetchmail)
#
# Remove the "exit 0" line if you want only want to run fetchmail when the
# PPP link is up.
#

exit 0

if [ -x /etc/init.d/fetchmail ]; then
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d --quiet fetchmail stop || true
	else
		/etc/init.d/fetchmail stop || true
	fi
fi
