var exports = {},
    _dewExec = false;

var _global = typeof globalThis !== "undefined" ? globalThis : typeof self !== "undefined" ? self : global;

export function dew() {
  if (_dewExec) return exports;
  _dewExec = true;
  // Generated by CoffeeScript 1.11.1

  /*
    ExternalEditor
    Kevin Gravier <kevin@mrkmg.com>
    MIT
   */
  (function () {
    var LaunchEditorError,
        extend = function (child, parent) {
      for (var key in parent) {
        if (hasProp.call(parent, key)) child[key] = parent[key];
      }

      function ctor() {
        (this || _global).constructor = child;
      }

      ctor.prototype = parent.prototype;
      child.prototype = new ctor();
      child.__super__ = parent.prototype;
      return child;
    },
        hasProp = {}.hasOwnProperty;

    LaunchEditorError = function (superClass) {
      extend(LaunchEditorError, superClass);
      LaunchEditorError.prototype.message = 'Failed launch editor';

      function LaunchEditorError(original_error) {
        (this || _global).original_error = original_error;
      }

      return LaunchEditorError;
    }(Error);

    exports = LaunchEditorError;
  }).call(exports);
  return exports;
}