/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-indexeddb-mirror/app-indexeddb-mirror-worker.js
 */

/**
 * Class that implements a worker process negotiates connections from clients
 * in other threads, and operates on an IndexedDB database object store.
 */
declare class AppIndexedDBMirrorWorker {
}
